version: "3.6"

services:
  app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: go-grafana
      ports:
        - 3000:3000
      restart: always
  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - app
  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 5000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  prometheus-storage:
